egocylindrical_propagator_node:
  ros__parameters:
    use_sim_time: true
    sensors:
      observation_sources: ["semantic_depth"]
      semantic_depth:
        type: semantic_depth
        image_in: /D435/depth/image_raw
        info_in: /D435/depth/camera_info
        publish_update: true
        raytrace: true
    points_out: data
    filtered_points: filtered_points
    fixed_frame_id: odom
<<<<<<< HEAD
    orientation_fixed_frame_id: base_aligned
    origin_fixed_frame_id: D435_depth_optical_frame
    width: 512
=======
    orientation_fixed_frame_id: odom
    origin_fixed_frame_id: camera_depth_optical_frame
    width: 256
>>>>>>> ros2_humble
    height: 120